### PR TITLE
Fix exception due to illegal access to item in an empty map

### PR DESCRIPTION
**Pull request by shawngustaw**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shawngustaw** [comment]
@manueliglesias do you know anyone I can reach out to to get this reviewed/merged?

**Comment by shamseer-ahammed** [comment]
@manueliglesias waiting

**Comment by revmischa** [comment]
@manueliglesias we'd love to get a review on this please

**Comment by itzcull** [comment]
Eagerly waiting the graciousness of our AWS Dev overlords

**Comment by objectiveSee** [comment]
🦗🦗🦗🦗🦗

**Review by iartemiev — CHANGES_REQUESTED** [review]
Thanks for the contribution and apologies that it took us so long to review. We'll get this change merged and released ASAP.

**Review by iartemiev — APPROVED** [review]

**Comment by shawngustaw** [comment]
Thanks so much @iartemiev !

**Comment by iartemiev** [comment]
@shawngustaw was just released in `aws-appsync-subscription-link@3.1.3`

**Comment by hgaron-blockbar** [comment]
@iartemiev  When I upgraded `aws-appsync-subscription-link` from `3.0.9` to `3.1.3`, this patch broke my subscriptions. Previously, the error described (for which this patch intended to fix) would only affect slower network conditions. Now it breaks subscriptions entirely:
image

Note that after upgrading to `3.1.3`, I rolled back my upgrade to `3.0.9` and applied this patch manually to my `node_modules`, and received that same result. It appears this patch is the result.

Note that I'm am also using the following libraries:
image
image

This is for a web app, not a mobile app.

**Pull request merged**
