### PR TITLE
Solution for large bundle size

### PR DESCRIPTION
**Pull request by morrys**
https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/203

Reduced dependency on AWS SDK. Now it is only necessary for authentication through AWS-IAM and to use the complex object to upload files to S3.

Examples of use:

// not include aws-sdk
import AWSAppSyncClient from "aws-appsync";
import { authCognito } from "aws-appsync/lib/link/auth";
const client = new AWSAppSyncClient({
url: 'some url',
region: 'some region',
authType: authCognito("some key"),
})

//includes only signer.js, aws-sdk/lib/credentials and aws-sdk/global
import AWSAppSyncClient from "aws-appsync";
import { authIAM } from "aws-appsync/lib/link/auth/aws";
const client = new AWSAppSyncClient({
url: 'some url',
region: 'some region',
authType: authIAM(credentials),
})

// includes all the necessary dependencies
import AWSAppSyncClient from "aws-appsync";
import { authIAM } from "aws-appsync/lib/link/auth/aws";
const client = new AWSAppSyncClient({
url: 'some url',
region: 'some region',
authType: authIAM(credentials),
complexObjects: new ComplexObjectLink(complexObjectsCredentials),
})

### CODE REVIEW

**Comment by elorzafe** [comment]
@morrys Thanks for your PR, we are going to review this next week.

**Comment by aralroca** [comment]
In the last release the bundle size increase... 

image

**Comment by stephankaag** [comment]
Any updates @manueliglesias @elorzafe?

**Comment by morrys** [comment]
Reduced dependency on subscription and paho-mqtt when not necessary

// includes all the necessary dependencies
import AWSAppSyncClient from "aws-appsync";
import { authIAM } from "aws-appsync/lib/link/auth/aws";
import { ComplexObjectLink } from "aws-appsync/lib/link/complex";
import { subscription } from "aws-appsync/lib/link/subscription";
const client = new AWSAppSyncClient({
url: 'some url',
region: 'some region',
authType: authIAM(credentials),
complexObjects: new ComplexObjectLink(complexObjectsCredentials),
subscription: subscription,
})

**Comment by morrys** [comment]
hi, is it possible to have updates on this PR before I resolve other file conflicts? I preferred to use relay instead of apollo to reduce the bundle and
I have created these repositories: the first one is [react-relay-offline](https://github.com/morrys/react-relay-offline) that is an extension of Relay Modern (v3.0.0 or v.4.0.0) for offline capabilities and the second one is [react-relay-appsync](https://github.com/morrys/react-relay-appsync) for uploading files to S3 and for authentication in aws iam.

Opinions and suggestions are welcome to improve these libraries.
Thanks

**Comment by tehOPEologist** [comment]
can we get an update on the status of this PR?  reducing bundle size is hugely important for web applications wanting to leverage aws-appsync, and currently this package takes up a huge portion of the total bundled size.

**Comment by morrys** [comment]
I close the PR as it is no longer in line with the current code base. Now two new libraries have been created: aws-appsync-auth-link aws-appsync-subscription-link

**Pull request closed without merging**
