### PR TITLE
Potentially fix double mutation bug

### PR DESCRIPTION
**Pull request by rivertam**
Completely unsure if this is a good fix.

An attempt to address #30 

I don't really understand how this library works or what my fix does, so please take with a grain of salt. I would _really_ like this issue resolved, as putting in optimistic results for some mutations results in very hard to work-around behavior.

### CODE REVIEW

**Comment by rivertam** [comment]
Also, to be honest, I made this edit in GitHub's code editor because I only have running access to the compiled version. I don't think so, but I might have made a mistake as stupid as a syntax error. A _very_ brief trial doing the same thing on the compiled node module resulted in the issue being fixed and no other bugs perceived.

**Comment by nicokruger** [comment]
This seems to be working for me for now, thanks.

**Comment by nicokruger** [comment]
Please note I still believe there is another bug, somewhere in the stack even with his fix.

This solves the double POST problem when you have no optimsticResponse, but I still believe something wonky is happening when you do provide an optimisticResponse. In my project, the real response from the server is never replacing the optimisticResponse. Also, should the initial mutation fail and you have provided an opstimisticResponse, the optimisticResponse is not rolled back. It's almost as if the error is not picked up at all.

With this patch, however, the "standard" behaviour of having no optimisticResponse seems to be working 100% now.

Thanks

**Comment by manueliglesias** [comment]
Hey @rivertam, @nicokruger  , thank you so much for your contributions!

#34 should address this plus some other special cases. Also, if you don't want to have offline capabilities, you can completely skip them (see #33 for usage)

Feel free to re-open or create a new issue as needed if you still see problems.

**Comment by nicokruger** [comment]
Hi @manueliglesias 

Just to let you know, with 1.0.8 the double mutation bug, as well as the bugs I mentioned with the optimisticResponse never being replaced by the server response, or being reverted in the case of an error, are fixed.

Thanks so much!

**Pull request closed without merging**
