### PR TITLE
fix(subscriptions):Improve SSR support

### PR DESCRIPTION
**Pull request by manueliglesias**
*Issue #, if available:*
Fixes: #10 
Fixes: #77 
Fixes: #82 
Fixes: #104 

*Description of changes:*
Add copy of paho-client to vendor folder with patch from eclipse/paho.mqtt.javascript#153

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by damonmaria** [comment]
This works great. Just to point out the documentation at https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-javascript.html needs to be updated.

**Comment by Necmttn** [comment]
Still having some issues when I try to build with Gatsby.
on build throw's error 
```
TypeError: resolveClient is not a function
```
anyone have clue how to solve that issue?

**Comment by camdav** [comment]
Hi, i'm having this error. Have you found a solution?

**Comment by bart** [comment]
I have the exact same error. Any solution so far?

**Pull request merged**
